import Form from '@/components/Form';
import FormButtonPage from '@/components/FormButtonPage';
import { Metadata } from 'next';

export const metadata: Metadata = {
	title: 'Log in page',
	description: 'Generated by create next app',
};

export default function LogIn() {
	return (
		<>
			<div className="flex flex-col justify-center w-full h-screen lg:h-3/4">
				<h2 className="text-gradient mt-12 2xs:mt-6">
					Log in
				</h2>
				<Form>
					<p className="text-xl text-[var(--second-color)] mt-4 md:text-2xl md:mt-8">
						Don&rsquo;t have an account?
					</p>
					<div className="text-xl md:text-2xl md:mt-6">
						<FormButtonPage href="/signup">Sign up</FormButtonPage>
					</div>
				</Form>
			</div>
		</>
	);
}
