import type { Metadata } from 'next';
import { Montserrat } from 'next/font/google';
import './globals.css';
import BackgroundLottie from '@/components/BackgroundLottie';

const montserrat = Montserrat({
	style: ['normal'],
	subsets: ['latin'],
	weight: '300',
});

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body
				className={`${montserrat.className} antialiased bg-[var(--main-color)]`}>
				<BackgroundLottie />
				{children}
			</body>
		</html>
	);
}
