import NotesPageClient from './NotesPageClient';
import { FolderTypes } from '@/types/FolderTypes';
import { NoteTypes } from '@/types/NotesType';
import { Metadata } from 'next';

export const metadata: Metadata = {
	title: 'Notes page',
	description: 'Generated by create next app',
};

export default async function NotesPage() {
	const folders: FolderTypes[] = [];
	const notes: NoteTypes[] = [];

	return <NotesPageClient initialFolders={folders} initialNotes={notes} />;
}
